In [13]:
import numpy as np
import matplotlib.pyplot as plt

a=10
v=np.array([10,20,30])
dimension1 = np.array([[5,9],[15,20]])
dimension2 = np.array([[15,10],[1,2]])
Matrix3d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Scalar ", a)
print("dimension1:", dimension1)
print("dimension2:", dimension2)
print("dimensions Addition: \n", dimension1 + dimension2)
print("Matrix3d \n", Matrix3d)

print("Scalar Multiply :", 2 * dimension1)

print("Dot Product:", np.dot(dimension1, dimension2))




Scalar  10
dimension1: [[ 5  9]
 [15 20]]
dimension2: [[15 10]
 [ 1  2]]
dimensions Addition: 
 [[20 19]
 [16 22]]
Matrix3d 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Scalar Multiply : [[10 18]
 [30 40]]
Dot Product: [[ 84  68]
 [245 190]]
